In [40]:
import pandas as pd

xls = r'O:\Payroll Services\Unit4\Batch#4\KCSC406-LENOVOHK-Lenovo\PaySummary_20191008.xlsx'

df_pt = pd.read_excel(xls, sheet_name=1)
df_ps = pd.read_excel(xls, sheet_name=0)

In [47]:
for i in range(2014,2020):
    df_ps_yearly = df_ps[df_ps.PayRunCode.str.contains(str(i))]
    df_pt_yearly = df_pt[df_pt.PayRunCode.str.contains(str(i))]
    
    with pd.ExcelWriter(r'O:\Payroll Services\Unit4\Batch#4\KCSC406-LENOVOHK-Lenovo\PaySummary_{}.xlsx'.format(i)) as writer: 
        df_ps_yearly.to_excel(writer, 'PaySummary', index=False)
        df_pt_yearly.to_excel(writer, 'PayTransaction', index=False)

In [49]:
df_ps[df_ps.PayRunCode.str.contains(str('2014'))]

,EmployeeCode,PayRunCode,BasicPay,NetPay,MPFEmployee,MPFEmployeeMandatory,MPFEmployeeVoluntary,MPFEmployeePaidOut,MPFEmployeePaidOutMandatory,MPFEmployeePaidOutVoluntary,MPFEmployer,MPFEmployerMandatory,MPFEmployerVoluntary,MPFEmployerPaidOut,MPFEmployerPaidOutMandatory,MPFEmployerPaidOutVoluntary,MPFPaidOutFlag
4,600485,HK2014-03-003,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0
5,606902,HK2014-03-003,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0
6,620423,HK2014-04-003,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0
7,502043,HK2014-09-003,51226.95,63273.85,1500.00,1500.00,0.0,1500.00,1500.00,0.0,4423.32,1500.00,2923.32,4423.32,1500.00,2923.32,0
8,605040,HK2014-09-003,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,72076,HK2014-12-004,28600.00,49086.50,1500.00,1500.00,0.0,1500.00,1500.00,0.0,1500.00,1500.00,0.00,1500.00,1500.00,0.00,0
422,73094,HK2014-12-004,19440.00,18468.00,972.00,972.00,0.0,972.00,972.00,0.0,972.00,972.00,0.00,972.00,972.00,0.00,0
423,73366,HK2014-12-004,16720.00,25052.24,1318.54,1318.54,0.0,1318.54,1318.54,0.0,1318.54,1318.54,0.00,1318.54,1318.54,0.00,0
424,73569,HK2014-12-004,21840.00,38498.58,1500.00,1500.00,0.0,1500.00,1500.00,0.0,1500.00,1500.00,0.00,1500.00,1500.00,0.00,0
425,74690,HK2014-12-004,49700.00,87920.24,1500.00,1500.00,0.0,1500.00,1500.00,0.0,2485.00,1500.00,985.00,2485.00,1500.00,985.00,0